AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.1


inherit_gem:
  rubocop-ronin: rubocop.yml

#
# ronin-nmap specific exceptions
#
Style/ExplicitBlockArgument:
  Exclude:
    - 'lib/ronin/nmap/converters/csv.rb'
